import { ThemeProvider } from "@/context/themeContext";
import StyledComponentsRegistry from "@/app/registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalStyle from "./globalStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{margin:0, padding:0,boxSizing:"border-box"}} >
      <StyledComponentsRegistry>
      <GlobalStyle/>
      <ThemeProvider>
      {children}
      </ThemeProvider>
      </StyledComponentsRegistry>
      
      </body> 
      
    </html>
  );
}
