//_________________________________________ USER ENDPOINTS ______________________________________//

//1 - Signup
//Its possible define users roles if wanted => "role":"admin". This information is optional and if none value was give by body, user will assume "normal" as role.

POST http://localhost:3003/users/signup
Content-Type: application/json

{
   "name": "aversin", 
   "email": "laversiiii@gmail.com",
   "password": "123456",
   "role": "admin"   
}

###

// 2 - Login

POST http://localhost:3003/users/login
Content-Type: application/json

{
   "email": "laversiiii@gmail.com", 
   "password": "123456"
}

###

// 3 Get all USERS
GET http://localhost:3003/users/getAll
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWE3ZTA5LTMzZmQtNDBjNC1hM2JiLWE0YzI1NmNiYzMwNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY5NDEzNTM5NSwiZXhwIjoxNjk0MTQ2MTk1fQ.QYIIHoHnuOZaHpqZzr50cfGbLz0wpa8-Blp_bDV4d8Y
###

// 4 Get USERS by ID

GET http://localhost:3003/users/1/profile/
Content-Type: application/json
###


// 5 Get all RECIPES

GET http://localhost:3003/recipes/all
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWE3ZTA5LTMzZmQtNDBjNC1hM2JiLWE0YzI1NmNiYzMwNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY5NDEzNTM5NSwiZXhwIjoxNjk0MTQ2MTk1fQ.QYIIHoHnuOZaHpqZzr50cfGbLz0wpa8-Blp_bDV4d8Y
###

//  - CREATE NEW RECIPE - requires authorization
POST http://localhost:3003/recipes/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNWE3ZTA5LTMzZmQtNDBjNC1hM2JiLWE0YzI1NmNiYzMwNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY5NDEzNTM5NSwiZXhwIjoxNjk0MTQ2MTk1fQ.QYIIHoHnuOZaHpqZzr50cfGbLz0wpa8-Blp_bDV4d8Y

{
    "title": "i shake it off",
    "description": "i shake it off",
    "ingredients": "i shake it off",
    "cookTime":"",
    "instructions": "bota tudo pra cozinhar espera meia hora e vai ficar muito bom",
    "photo":"feijuquinha.jpg"

}
###

